server.port=8082
core.service.url=http://localhost:8081

# Docker pgvector DB Connection (Remains identical)
spring.datasource.url=jdbc:postgresql://localhost:5432/compliance_audit_db
spring.datasource.username=dev_admin
spring.datasource.password=password
spring.ai.vectorstore.pgvector.table-name=compliance_rules
#spring.ai.vectorstore.pgvector.initialize-schema=true

#AWS Global Authentication Configuration
spring.ai.aws.region=us-east-1
spring.ai.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.ai.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}

spring.ai.model.chat=bedrock-converse
spring.ai.bedrock.converse.chat.options.model=us.amazon.nova-lite-v1:0

spring.ai.model.embedding=bedrock-titan
spring.ai.bedrock.titan.embedding.model=amazon.titan-embed-text-v1

spring.ai.vectorstore.pgvector.initialize-schema=true

# Docker PGVector Connection Properties
spring.ai.vectorstore.pgvector.dimensions=1536

spring.ai.bedrock.titan.embedding.input-type=text
