spring.application.name=core

server.port=8081
# Connecting directly to the Docker PostgreSQL container instance
spring.datasource.url=jdbc:postgresql://localhost:5432/compliance_audit_db
spring.datasource.username=dev_admin
spring.datasource.password=password

# Hibernate configuration to automatically create tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
